//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMusicDesktop.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniMusicDesktop.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账户 的本地化字符串。
        /// </summary>
        public static string AccountText {
            get {
                return ResourceManager.GetString("AccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入账号 的本地化字符串。
        /// </summary>
        public static string AccountWatermarkText {
            get {
                return ResourceManager.GetString("AccountWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四月 的本地化字符串。
        /// </summary>
        public static string AprilText {
            get {
                return ResourceManager.GetString("AprilText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 八月 的本地化字符串。
        /// </summary>
        public static string AugustText {
            get {
                return ResourceManager.GetString("AugustText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选时间段 的本地化字符串。
        /// </summary>
        public static string BarSelectTipsText {
            get {
                return ResourceManager.GetString("BarSelectTipsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string CaptchaText {
            get {
                return ResourceManager.GetString("CaptchaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string CaptchaWatermarkText {
            get {
                return ResourceManager.GetString("CaptchaWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 换一张 的本地化字符串。
        /// </summary>
        public static string ChangeCaptchaText {
            get {
                return ResourceManager.GetString("ChangeCaptchaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前邮箱 的本地化字符串。
        /// </summary>
        public static string CurrentEmailText {
            get {
                return ResourceManager.GetString("CurrentEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 十二月 的本地化字符串。
        /// </summary>
        public static string DecemberText {
            get {
                return ResourceManager.GetString("DecemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二月 的本地化字符串。
        /// </summary>
        public static string FebruaryText {
            get {
                return ResourceManager.GetString("FebruaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找回密码 的本地化字符串。
        /// </summary>
        public static string FindPwdTitleText {
            get {
                return ResourceManager.GetString("FindPwdTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取验证码 的本地化字符串。
        /// </summary>
        public static string GetCaptchaText {
            get {
                return ResourceManager.GetString("GetCaptchaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一月 的本地化字符串。
        /// </summary>
        public static string JanuaryText {
            get {
                return ResourceManager.GetString("JanuaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 七月 的本地化字符串。
        /// </summary>
        public static string JulyText {
            get {
                return ResourceManager.GetString("JulyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 六月 的本地化字符串。
        /// </summary>
        public static string JuneText {
            get {
                return ResourceManager.GetString("JuneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三月 的本地化字符串。
        /// </summary>
        public static string MarchText {
            get {
                return ResourceManager.GetString("MarchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 五月 的本地化字符串。
        /// </summary>
        public static string MayText {
            get {
                return ResourceManager.GetString("MayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        public static string MonthString {
            get {
                return ResourceManager.GetString("MonthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        public static string MRoleText {
            get {
                return ResourceManager.GetString("MRoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌曲详情 的本地化字符串。
        /// </summary>
        public static string MusicDetailText {
            get {
                return ResourceManager.GetString("MusicDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐清单 的本地化字符串。
        /// </summary>
        public static string MusicMarketText {
            get {
                return ResourceManager.GetString("MusicMarketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string NewPwdText {
            get {
                return ResourceManager.GetString("NewPwdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入新密码 的本地化字符串。
        /// </summary>
        public static string NewPwdWatermarkText {
            get {
                return ResourceManager.GetString("NewPwdWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 十一月 的本地化字符串。
        /// </summary>
        public static string NovemberText {
            get {
                return ResourceManager.GetString("NovemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 十月 的本地化字符串。
        /// </summary>
        public static string OctoberText {
            get {
                return ResourceManager.GetString("OctoberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        public static string PasswordWatermarkText {
            get {
                return ResourceManager.GetString("PasswordWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string QuitText {
            get {
                return ResourceManager.GetString("QuitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果没有账号？ 的本地化字符串。
        /// </summary>
        public static string RegisterAccountWatermarkText {
            get {
                return ResourceManager.GetString("RegisterAccountWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string RepeatNewPwdText {
            get {
                return ResourceManager.GetString("RepeatNewPwdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请再次输入密码 的本地化字符串。
        /// </summary>
        public static string RepeatNewPwdWatermarkText {
            get {
                return ResourceManager.GetString("RepeatNewPwdWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置密码 的本地化字符串。
        /// </summary>
        public static string ResetPwdText {
            get {
                return ResourceManager.GetString("ResetPwdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 九月 的本地化字符串。
        /// </summary>
        public static string SeptemberText {
            get {
                return ResourceManager.GetString("SeptemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string SubmitText {
            get {
                return ResourceManager.GetString("SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐桌面应用系统 的本地化字符串。
        /// </summary>
        public static string SystemTitleText {
            get {
                return ResourceManager.GetString("SystemTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人用户 的本地化字符串。
        /// </summary>
        public static string UserRoleText {
            get {
                return ResourceManager.GetString("UserRoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        public static string YearString {
            get {
                return ResourceManager.GetString("YearString", resourceCulture);
            }
        }
    }
}
